services:
  # Web App Service
  web-app:
    build: ./web_app  # Build the Docker image from the Dockerfile in the web-app directory
    ports:
      - "8080:8080"  # Expose web app on port 8080 of the host machine
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./.env:/app/.env  # Share .env file with the app container
    command: python -u app.py  # Command to run the web app

  # MongoDB Service
  mongodb:
    image: mongo:latest  # Use latest official MongoDB image
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    volumes:
      - mongo_data:/data/db  # Volume for MongoDB data persistence
      - ./.env:/app/.env  # Share .env file with MongoDB container
    networks:
      - app-network

      
# Persistent Volume for MongoDB Data
volumes:
  mongo_data:

# Custom Network for Container Communication
networks:
  app-network:
    driver: bridge  # Ensure all services can communicate over this network