name: Web App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    env:
      MONGO_URI: mongodb://localhost:27017
      MONGO_DBNAME: country_wordle

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r web_app/requirements.txt
          pip install requests

      - name: Run tests
        run: |
          python -m pytest tests/test_web_app.py --maxfail=5 --disable-warnings -q
